# Generated by Django 4.2.11 on 2024-04-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "obtained_title",
                    models.CharField(max_length=100, verbose_name="Título Obtenido"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                ("obtained_date", models.DateField(verbose_name="Fecha de obtención")),
            ],
            options={
                "verbose_name": "Formación",
                "verbose_name_plural": "Cursos",
                "ordering": ["-obtained_date"],
            },
        ),
    ]
