# Generated by Django 4.2.11 on 2024-04-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formacion",
            old_name="title",
            new_name="name",
        ),
    ]
