# Generated by Django 4.2.11 on 2024-04-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_formacion_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Conocimiento")),
                ("image", models.ImageField(upload_to="skills", verbose_name="Imagen")),
            ],
            options={
                "verbose_name": "Conocimiento",
                "verbose_name_plural": "Conocimientos",
            },
        ),
    ]
