# Generated by Django 4.2.11 on 2024-04-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_project_options_alter_project_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="projects", verbose_name="Imagen"),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(
                blank=True, max_length=180, null=True, verbose_name="Enlace"
            ),
        ),
    ]
